
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        lowerCaseServiceId: true
      routes:
        - id: product-microservice
          uri: lb://PRODUCT-MICROSERVICE
          predicates:
          - Path=/api/products/**,/api/categories/**,/product-microservice/v3/api-docs
        - id: stock-microservice
          uri: lb://STOCK-MICROSERVICE
          predicates:
            - Path=/api/stock/**,/stock-microservice/v3/api-docs
        - id: booking-microservice
          uri: lb://BOOKING-MICROSERVICE
          predicates:
            - Path=/api/booking/**,/booking-microservice/v3/api-docs
    loadBalancer:
      ribbon:
        enabled: false

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

server:
  servlet:
    context-path: /
  port:
    8080

springDoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Microservice
        primaryName: API Gateway Microservice
      - url: /product-microservice/v3/api-docs
        name: Product Microservice
        primaryName: Product Microservice
      - url: /booking-microservice/v3/api-docs
        name: Booking Microservice
        primaryName: Booking Microservice
      - url: /stock-microservice/v3/api-docs
        name: Stock Microservice
        primaryName: Stock Microservice